---
extends: default

ignore:
  - .roles/
  - .ansible/
  - .github/
  - .pre-commit-config.yaml

rules:
  line-length:
    max: 200
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start:
    present: true
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
