---
# UniFi role defaults

# Service configuration
unifi_service_name: unifi

# Directory paths
unifi_config_dir: /etc/unifi

# Quadlet
unifi_quadlet_dir: /etc/containers/systemd

# User configuration
unifi_user: ansible
unifi_user_uid: 1000
unifi_user_gid: 1000

# MongoDB configuration
unifi_mongodb_user: unifi
unifi_mongodb_password: changeme
unifi_mongodb_database: unifi

# Traefik configuration
unifi_traefik_config_dir: /etc/traefik
unifi_service_domain: ""
unifi_cert_dir: /etc/unifi/certs

# Backup configuration
unifi_backup_image_name: backup-toolkit
unifi_backup_image_tag: local
unifi_backup_cron: "*-*-* 04:00:00"
unifi_backup_aws_access_key: ""
unifi_backup_aws_secret_access_key: ""
unifi_backup_aws_region: eu-west-2
unifi_backup_s3_bucket: home-server-backup.iamrobertyoung.co.uk
unifi_backup_mosquitto_host: mosquitto.local.iamrobertyoung.co.uk
unifi_backup_mosquitto_username: "home-assistant"
unifi_backup_mosquitto_password: ""
